{% set version = "asp3.4.0_alpha" %} # synched up to isis dependencies for this version

package:
    name: libelas
    version: {{ version }}

source:
  git_url: git@github.com:NeoGeographyToolkit/libelas.git

build:
    number: 0

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake 3.27.9

    host:
        - llvm-openmp 16.0.6
        - openjpeg 2.5.0
        - libpng 1.6.47
        - libtiff 4.5.1
        - zlib 1.3.1
    run:
        - llvm-openmp 16.0.6
        - openjpeg 2.5.0
        - libpng 1.6.47
        - libtiff 4.5.1
        - zlib 1.3.1

test:
    files:
        imports:
        commands:
        comment:

about:
    home: https://github.com/NeoGeographyToolkit/libelas
    license: APACHE II
    summary: An Efficient Large-scale Stereo Matching Algorithm

extra:
  recipe-maintainers:
    - oleg.alexandrov@gmail.com
