{% set version = "isis7" %} # synched up to isis dependencies for this version

package:
    name: libelas
    version: {{ version }}

source:
  git_url: git@github.com:NeoGeographyToolkit/libelas.git

build:
    number: 0

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - llvm-openmp             # [osx]
#       - libgomp                 # [linux]

    host:
        - jpeg 9e
        - openjpeg 2.3.0
        - libpng 1.6.39
        - libtiff 4.4.0
        - zlib 1.2.13
    run:
        - jpeg 9e
        - openjpeg 2.3.0
        - libpng 1.6.39
        - libtiff 4.4.0
        - zlib 1.2.13

test:
    files:
        imports:
        commands:
        comment:

about:
    home: https://github.com/NeoGeographyToolkit/libelas
    license: APACHE II
    summary: An Efficient Large-scale Stereo Matching Algorithm

extra:
  recipe-maintainers:
    - oleg.alexandrov@gmail.com
