{% set version = "isis6" %} # synched up to isis dependencies for this version

package:
    name: libelas
    version: {{ version }}

source:
  git_url: git@github.com:NeoGeographyToolkit/libelas.git
  git_tag: e8fdfa8

build:
    number: 0

requirements:
    build:
# Use the local compiler for OSX. See build.sh for details.
        - {{ compiler('c') }}     # [linux]
        - {{ compiler('cxx') }}   # [linux]
        - cmake
        - llvm-openmp             # [osx]
#       - libgomp                 # [linux]

    host:
        - jpeg 9e
        - openjpeg 2.3.0
        - libpng 1.6.37
        - libtiff 4.0.10
        - zlib 1.2.11
    run:
        - jpeg 9*
        - openjpeg 2.3.0
        - libpng 1.6.37
        - libtiff 4.0.10
        - zlib 1.2.11

test:
    files:
        imports:
        commands:
        comment:

about:
    home:
    license: APACHE II
    summary:

extra:
  recipe-maintainers:
    - oleg.alexandrov@gmail.com
